### ISSUE TITLE
Private Call - It seems will ring indefinitely if no one picking it up? (How to make it stop ringing?)

### ISSUE THREAD

**Issue by ck0099** [pytgcalls/pytgcalls#274]
In private call, there seems no option to set a timeout (i.e. ring about 10 seconds, if no one pick it up, just hang up) to hang up the call automatically?

**Comment by ck0099** [comment]
I guess to stop a call you do this?

https://pytgcalls.github.io/PyTgCalls/Basic%20Methods/Leave%20Call

**Comment by ck0099** [comment]
I tried the following, however the execution just keep get stuck at play, it never gets to:

print("[2] Wait some seconds ")

Than how can I terminate the call (while it is still ringing)?

`
from pyrogram import Client

from pytgcalls import idle
from pytgcalls import PyTgCalls
from pytgcalls.types import MediaStream

app = Client(
    'py-tgcalls',
    api_id=1234,
    api_hash='1234',
)

call_py = PyTgCalls(app)
chat_id = 1234
call_py.start()
audio_file = 'http://docs.evostream.com/sample_content/assets/sintel1m720p.mp4'


print("[1] Calling user 1234...")

call_py.play(
    chat_id,
    MediaStream(
        audio_file,
    ),
)
# idle()

print("[2] Wait some seconds ")

import time
time.sleep(5)


print("[3] Tiemout 5 second reached, stop the call.")

call_py.leave_call(
 chat_id,
)

`

**Comment by Laky-64** [comment]
The ringing is something more "client side" as I've understood, but It should return that:
https://github.com/pytgcalls/pytgcalls/blob/master/pytgcalls/methods/stream/play.py#L145-L147

How is possible it is returning CancelledError instead to you?

Since here I start a wait with a timeout:
https://github.com/pytgcalls/pytgcalls/blob/master/pytgcalls/methods/stream/play.py#L123-L125

**Comment by ck0099** [comment]
Hi @Laky-64 

So I ran this code:

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/cfea856a-f668-4856-9284-4dd02056abdf" />

Than I got this error message, while the call on my telegram app is still ringing.

<img width="297" alt="Image" src="https://github.com/user-attachments/assets/81456bba-f54e-4750-80d7-ccd6d9654e83" />


(tgCall_v01) PS C:\Users\jpom\Documents\py\tgCall_v01> python .\bot_call_simple_v01.py
PyTgCalls v2.0.6 powered by NTgCalls v1.2.3, Copyright (C) 2021-2025 Laky-64 <https://github.com/Laky-64>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

[1] Calling user 1234...
Traceback (most recent call last):
  File "C:\Users\jpom\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jpom\Documents\py\tgCall_v01\lib\site-packages\pytgcalls\methods\stream\play.py", line 123, in play
    result: RawCallUpdate = await asyncio.wait_for(
  File "C:\Users\jpom\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jpom\Documents\py\tgCall_v01\bot_call_simple_v01.py", line 29, in <module>
    call_py.play(
  File "C:\Users\jpom\Documents\py\tgCall_v01\lib\site-packages\pytgcalls\sync.py", line 55, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Users\jpom\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\jpom\Documents\py\tgCall_v01\lib\site-packages\pytgcalls\mutex.py", line 9, in async_wrapper
    return await func(*args, **kwargs)
  File "C:\Users\jpom\Documents\py\tgCall_v01\lib\site-packages\pytgcalls\statictypes.py", line 96, in async_wrapper
    return await func(*args, **kwargs)
  File "C:\Users\jpom\Documents\py\tgCall_v01\lib\site-packages\pytgcalls\mtproto_required.py", line 23, in async_wrapper
    return await func(*args, **kwargs)
  File "C:\Users\jpom\Documents\py\tgCall_v01\lib\site-packages\pytgcalls\methods\stream\play.py", line 147, in play
    raise TimedOutAnswer()
pytgcalls.exceptions.TimedOutAnswer: Timed out waiting for an answer
(tgCall_v01) PS C:\Users\jpom\Documents\py\tgCall_v01>

**Comment by ck0099** [comment]
and interestingly I found most code on github uses GroupCallConfig, can't find any sample code using CallConfig :P

Maybe I am first to try? haha

**Comment by ck0099** [comment]
But the call will just keep ringing indefinitely, which is an issue. Even the telegram client will not cancel/stop the call.

How do we deal with this?

**Comment by Laky-64** [comment]
> But the call will just keep ringing indefinitely, which is an issue. Even the telegram client will not cancel/stop the call.
> 
> How do we deal with this?

Mhh, I'll try to take look about this when I'll be free, currently the only way is by doing it manually by using MTProto itself (e.g. pyrogram or etc)

**Comment by ck0099** [comment]
Thank you so much Laky! That will be great!

**Comment by ck0099** [comment]
Hi @Laky-64, I looked into pyrogram to find ways to cancel the on-going call ringing initiated by pytgcalls, however it seems pyrogram's function "discard-call" need info about the ringing call.

https://docs.pyrogram.org/telegram/functions/phone/discard-call

Any advice on temporary solution on how we can use pytgcalls to initiate the call, and use pyrogram to terminate the call after a timeout period if no one picks it up?

**Comment by Laky-64** [comment]
Hi @ck0099, by the way I'm working on a fix in the beta version of PyTgCalls by directly closing after the timeout, I'll reach you when the update will be ready

**Comment by ck0099** [comment]
Super awesome, thank you so much @Laky-64 !! :D

**Comment by Laky-64** [comment]
Fixed in this commit
https://github.com/pytgcalls/pytgcalls/commit/d9a82b11b948460206948b3c09486c222ef45a05

**Comment by ck0099** [comment]
sorry to ask a stupid question.

In python requirement.txt, how can I load such fixed commit? or how should I get such version to work in my venv?

Thank you so much @Laky-64

**Comment by Laky-64** [comment]
For now just use `git+https://github.com/pytgcalls/pygcalls@dev`

**Comment by ck0099** [comment]
Hi @Laky-64 , I noticed something very interesting from the current released version vs the latest dev version.

[Current Release]
pyrogram==2.0.106
py-tgcalls==2.0.6
(1) The call does not timeout automatically.
(2) Console (powershell) control is returned to the user after the function call is finished.

[Dev Release]
pyrogram==2.0.106
py-tgcalls @ git+https://github.com/pytgcalls/pytgcalls@7a401f9b9d4c53e9d0dcb35785ebb4756304f8ba
(1) The call will timeout automatically.
(2) However, console (powershell) control DOES NOT returned to the user after the function call is finished.

**Comment by ck0099** [comment]
I just updated to dev6, the console locking issue seems still persist.

**Comment by Laky-64** [comment]
> I just updated to dev6, the console locking issue seems still persist.

What do you mean with "locking issue"

**Comment by ck0099** [comment]
locking:
For example, I use powershell console to run the python script:

https://github.com/pytgcalls/pytgcalls/blob/master/example/docker_example/docker_example.py

python docker_example.py

The script will execute It will make a private call. However once the call is timeout (if no pickup), the console does not give me back control (i.e. I can't type anything in the console).

However this behaviour does not exist in the release version, but happens in the dev version.

**Comment by Laky-64** [comment]
Ok so, open a new issue, this issue is not related to this issue 

> locking: For example, I use powershell console to run the python script:
> 
> https://github.com/pytgcalls/pytgcalls/blob/master/example/docker_example/docker_example.py
> 
> python docker_example.py
> 
> The script will execute It will make a private call. However once the call is timeout (if no pickup), the console does not give me back control (i.e. I can't type anything in the console).
> 
> However this behaviour does not exist in the release version, but happens in the dev version.

**Comment by ck0099** [comment]
Ok will do!
